# Generated by Django 3.2.13 on 2022-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.TextField(),
        ),
    ]
